#############################################################################
# Makefile for building: qwt
# Generated by qmake (3.1) (Qt 5.9.6)
# Project:  qwt.pro
# Template: subdirs
# Command: C:\ldata1\qt\win64\vs2017\5.9.6\5.9.6\msvc2017_64\bin\qmake.exe -o Makefile qwt.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\ldata1\qt\win64\vs2017\5.9.6\5.9.6\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\ldata1\qt\win64\vs2017\5.9.6\5.9.6\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\ldata1\qt\win64\vs2017\5.9.6\5.9.6\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src \
		sub-textengines \
		sub-doc \
		sub-designer


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile 
sub-src-all-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile uninstall
sub-textengines-qmake_all: sub-src-qmake_all FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	cd textengines\ && $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && $(MAKE) -f Makefile qmake_all
sub-textengines: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile
sub-textengines-make_first-ordered: sub-src-make_first-ordered  FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile 
sub-textengines-make_first: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile 
sub-textengines-all-ordered: sub-src-all-ordered  FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile all
sub-textengines-all: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile all
sub-textengines-clean-ordered: sub-src-clean-ordered  FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile clean
sub-textengines-clean: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile clean
sub-textengines-distclean-ordered: sub-src-distclean-ordered  FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile distclean
sub-textengines-distclean: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile distclean
sub-textengines-install_subtargets-ordered: sub-src-install_subtargets-ordered  FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile install
sub-textengines-install_subtargets: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile install
sub-textengines-uninstall_subtargets-ordered: sub-src-uninstall_subtargets-ordered  FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile uninstall
sub-textengines-uninstall_subtargets: FORCE
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile uninstall
sub-doc-qmake_all: sub-textengines-qmake_all FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	cd doc\ && $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && $(MAKE) -f Makefile qmake_all
sub-doc: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile
sub-doc-make_first-ordered: sub-textengines-make_first-ordered  FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile 
sub-doc-make_first: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile 
sub-doc-all-ordered: sub-textengines-all-ordered  FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile all
sub-doc-all: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile all
sub-doc-clean-ordered: sub-textengines-clean-ordered  FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile clean
sub-doc-clean: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile clean
sub-doc-distclean-ordered: sub-textengines-distclean-ordered  FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile distclean
sub-doc-distclean: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile distclean
sub-doc-install_subtargets-ordered: sub-textengines-install_subtargets-ordered  FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile install
sub-doc-install_subtargets: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile install
sub-doc-uninstall_subtargets-ordered: sub-textengines-uninstall_subtargets-ordered  FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile uninstall
sub-doc-uninstall_subtargets: FORCE
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile uninstall
sub-designer-qmake_all: sub-doc-qmake_all FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	cd designer\ && $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && $(MAKE) -f Makefile qmake_all
sub-designer: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile
sub-designer-make_first-ordered: sub-doc-make_first-ordered  FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile 
sub-designer-make_first: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile 
sub-designer-all-ordered: sub-doc-all-ordered  FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile all
sub-designer-all: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile all
sub-designer-clean-ordered: sub-doc-clean-ordered  FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile clean
sub-designer-clean: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile clean
sub-designer-distclean-ordered: sub-doc-distclean-ordered  FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile distclean
sub-designer-distclean: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile distclean
sub-designer-install_subtargets-ordered: sub-doc-install_subtargets-ordered  FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile install
sub-designer-install_subtargets: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile install
sub-designer-uninstall_subtargets-ordered: sub-doc-uninstall_subtargets-ordered  FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile uninstall
sub-designer-uninstall_subtargets: FORCE
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile uninstall

Makefile: qwt.pro ..\5.9.6\5.9.6\msvc2017_64\mkspecs\win32-msvc\qmake.conf ..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\spec_pre.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\common\angle.conf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\qconfig.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\qt_functions.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\qt_config.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\common\msvc-version.conf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\toolchain.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\default_pre.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		qwtconfig.pri \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\resolve_config.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\default_post.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\precompile_header.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\warn_on.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\qmake_use.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\file_copies.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\win32\windows.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\testcase_targets.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\exceptions.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\yacc.prf \
		..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\lex.prf \
		qwt.pro
	$(QMAKE) -o Makefile qwt.pro
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\spec_pre.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\common\angle.conf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\common\msvc-desktop.conf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\qconfig.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\qt_functions.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\qt_config.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\exclusive_builds.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\common\msvc-version.conf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\toolchain.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\default_pre.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\win32\default_pre.prf:
qwtconfig.pri:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\resolve_config.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\default_post.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\precompile_header.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\warn_on.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\qmake_use.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\file_copies.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\win32\windows.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\testcase_targets.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\exceptions.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\yacc.prf:
..\5.9.6\5.9.6\msvc2017_64\mkspecs\features\lex.prf:
qwt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qwt.pro

qmake_all: sub-src-qmake_all sub-textengines-qmake_all sub-doc-qmake_all sub-designer-qmake_all FORCE

make_first: sub-src-make_first-ordered sub-textengines-make_first-ordered sub-doc-make_first-ordered sub-designer-make_first-ordered  FORCE
all: sub-src-all-ordered sub-textengines-all-ordered sub-doc-all-ordered sub-designer-all-ordered  FORCE
clean: sub-src-clean-ordered sub-textengines-clean-ordered sub-doc-clean-ordered sub-designer-clean-ordered  FORCE
distclean: sub-src-distclean-ordered sub-textengines-distclean-ordered sub-doc-distclean-ordered sub-designer-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-src-install_subtargets-ordered sub-textengines-install_subtargets-ordered sub-doc-install_subtargets-ordered sub-designer-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-textengines-uninstall_subtargets-ordered sub-doc-uninstall_subtargets-ordered sub-designer-uninstall_subtargets-ordered FORCE

sub-src-debug_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile debug
sub-textengines-debug_ordered: sub-src-debug_ordered 
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile debug
sub-doc-debug_ordered: sub-textengines-debug_ordered 
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile debug
sub-designer-debug_ordered: sub-doc-debug_ordered 
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile debug
debug: sub-src-debug_ordered sub-textengines-debug_ordered sub-doc-debug_ordered sub-designer-debug_ordered

sub-src-release_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile release
sub-textengines-release_ordered: sub-src-release_ordered 
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile release
sub-doc-release_ordered: sub-textengines-release_ordered 
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile release
sub-designer-release_ordered: sub-doc-release_ordered 
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile release
release: sub-src-release_ordered sub-textengines-release_ordered sub-doc-release_ordered sub-designer-release_ordered

sub-src-check_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile check
sub-textengines-check_ordered: sub-src-check_ordered 
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile check
sub-doc-check_ordered: sub-textengines-check_ordered 
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile check
sub-designer-check_ordered: sub-doc-check_ordered 
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile check
check: sub-src-check_ordered sub-textengines-check_ordered sub-doc-check_ordered sub-designer-check_ordered

sub-src-benchmark_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\src\src.pro ) && $(MAKE) -f Makefile benchmark
sub-textengines-benchmark_ordered: sub-src-benchmark_ordered 
	@if not exist textengines\ mkdir textengines\ & if not exist textengines\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd textengines\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\textengines\textengines.pro ) && $(MAKE) -f Makefile benchmark
sub-doc-benchmark_ordered: sub-textengines-benchmark_ordered 
	@if not exist doc\ mkdir doc\ & if not exist doc\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd doc\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\doc\doc.pro ) && $(MAKE) -f Makefile benchmark
sub-designer-benchmark_ordered: sub-doc-benchmark_ordered 
	@if not exist designer\ mkdir designer\ & if not exist designer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd designer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\ldata1\qt\win64\vs2017\qwt-6.1.3\designer\designer.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-benchmark_ordered sub-textengines-benchmark_ordered sub-doc-benchmark_ordered sub-designer-benchmark_ordered
install_qwtspec: FORCE
	@if not exist C:$(INSTALL_ROOT)\Qwt-6.1.3\features mkdir C:$(INSTALL_ROOT)\Qwt-6.1.3\features & if not exist C:$(INSTALL_ROOT)\Qwt-6.1.3\features exit 1
	-$(QINSTALL) C:\ldata1\qt\win64\vs2017\qwt-6.1.3\qwtconfig.pri C:$(INSTALL_ROOT)\Qwt-6.1.3\features\qwtconfig.pri
	-$(QINSTALL) C:\ldata1\qt\win64\vs2017\qwt-6.1.3\qwtfunctions.pri C:$(INSTALL_ROOT)\Qwt-6.1.3\features\qwtfunctions.pri
	-$(QINSTALL) C:\ldata1\qt\win64\vs2017\qwt-6.1.3\qwt.prf C:$(INSTALL_ROOT)\Qwt-6.1.3\features\qwt.prf

uninstall_qwtspec: FORCE
	-$(DEL_FILE) C:$(INSTALL_ROOT)\Qwt-6.1.3\features\qwt.prf
	-$(DEL_FILE) C:$(INSTALL_ROOT)\Qwt-6.1.3\features\qwtfunctions.pri
	-$(DEL_FILE) C:$(INSTALL_ROOT)\Qwt-6.1.3\features\qwtconfig.pri
	-$(DEL_DIR) C:$(INSTALL_ROOT)\Qwt-6.1.3\features 


install:install_subtargets install_qwtspec  FORCE

uninstall: uninstall_qwtspec uninstall_subtargets FORCE

FORCE:

